name: Smarthome_Zigbee_containers
name_module: Smarthome_Zigbee_containers
multiply: false
type: docker
containers:
  - name: Smarthome_Zigbee_containers
    config:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          CONTAINER_NAME: Smarthome_Zigbee_containers
          PORT: 3000
          NEXT_BASE_PATH: "/modules/Smarthome_Zigbee_containers"
      command: sh -c "cp -r /app/config_local/* /app/config && npm run start"
      restart: always
      environment:
        EXCHANGE_SERVICE_DATA: ${EXCHANGE_SERVICE_DATA}
        RABITMQ_PORT: ${RABITMQ_PORT}
        RABITMQ_HOST: ${RABITMQ_HOST}
        CONTAINER_NAME: Smarthome_Zigbee_containers
        PORT: 3000
      labels:
        - "traefik.http.routers.Smarthome_Zigbee_containers__ws.rule=PathPrefix(`/ws/Smarthome_Zigbee_containers`)"
        - "traefik.http.routers.Smarthome_Zigbee_containers__ws.service=Smarthome_Zigbee_containers__ws"
        - "traefik.http.services.Smarthome_Zigbee_containers__ws.loadbalancer.server.port=3000"
        - "traefik.http.routers.Smarthome_Zigbee_containers__ws.entrypoints=websecure"
        - "traefik.enable=true"
        - "traefik.http.routers.Smarthome_Zigbee_containers_http.rule=PathPrefix(`/modules/Smarthome_Zigbee_containers`)"
        - "traefik.http.routers.Smarthome_Zigbee_containers_http.entrypoints=web"
        - "traefik.http.routers.Smarthome_Zigbee_containers_http.middlewares=moduleauth@docker,module-Smarthome_Zigbee_containers-strip"
        - "traefik.http.routers.Smarthome_Zigbee_containers_http.service=Smarthome_Zigbee_containers"
        - "traefik.http.routers.Smarthome_Zigbee_containers_https.rule=PathPrefix(`/modules/Smarthome_Zigbee_containers`)"
        - "traefik.http.routers.Smarthome_Zigbee_containers_https.entrypoints=websecure"
        - "traefik.http.routers.Smarthome_Zigbee_containers_https.middlewares=moduleauth@docker,module-Smarthome_Zigbee_containers-strip"
        - "traefik.http.routers.Smarthome_Zigbee_containers_https.tls=true"
        - "traefik.http.routers.Smarthome_Zigbee_containers_https.service=Smarthome_Zigbee_containers"
        - "traefik.http.services.Smarthome_Zigbee_containers.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.module-Smarthome_Zigbee_containers-strip.stripprefixregex.regex=^/modules/Smarthome_Zigbee_containers"
      volumes:
        - ${CONFIGURATE_DIR}/Smarthome_Zigbee_containers:/app/config
  - name: Smarthome_Zigbee_containers_zigbee2mqtt
    config:
      image: koenkk/zigbee2mqtt
      restart: unless-stopped
      volumes:
        - ${CONFIGURATE_DIR}/Smarthome_Zigbee_containers_zigbee2mqtt:/app/data
        - /run/udev:/run/udev:ro
      environment:
        - TZ=Europe/Moscow
      privileged: true
